name: Update Pinterest Feed

on:
  schedule:
    - cron: '0 1 * * *'    # 4:00 Киев (летом UTC+3, зимой UTC+2)
  workflow_dispatch:  # Можно запускать вручную

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests lxml

      - name: Run script
        run: python filter_feed.py

      - name: Upload to Dropbox
  uses: dropbox/upload-to-dropbox@v1
  with:
    dropbox-access-token: ${{ secrets.DROPBOX_TOKEN }}
    local-path: './pinterest_in_stock_feed.xml'
    dropbox-path: '/pinterest_in_stock_feed.xml'
