name: Update Pinterest Feed

on:
  schedule:
    - cron: '0 1 * * *'    # 4:00 Киев (летом UTC+3, зимой UTC+2)
  workflow_dispatch:  # Можно запускать вручную

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests lxml

      - name: Run script
        run: python filter_feed.py

      - name: Upload to Dropbox
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
          -H "Authorization: Bearer ${{ secrets.DROPBOX_TOKEN }}" \
          -H "Dropbox-API-Arg: {\"path\":\"/pinterest_in_stock_feed.xml\",\"mode\":\"overwrite\"}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @pinterest_in_stock_feed.xml
